Repository Fastcampus-Youcandoit/frontend, pull requests merged in 2023-09, with the labels that each got.

#4 design: add Header layout
  .eslintrc.json
  .prettierrc
  package-lock.json
  package.json
  src/App.tsx
  src/assets/icons/header_icon/header_github_black_icon.png
  src/components/common/Header.tsx
  src/components/common/Logo.tsx
  src/custom.d.ts
  src/pages/Home.tsx
Labels: HTML&CSS

#6 Feature/5
  src/components/common/Header.tsx
  src/components/commute/CommuteButtonComponent.tsx
Labels: Refactor

#9 design: add Footer layout
  src/App.tsx
  src/components/common/Footer.tsx
Labels: HTML&CSS

#10 design: SideBar html, css 작업
  src/App.tsx
  src/assets/fonts/Font.css
  src/assets/icons/sidebar_icon/bottom_black_icon.png
  src/assets/icons/sidebar_icon/bottom_blue_icon.png
  src/assets/icons/sidebar_icon/project_black_icon.png
  src/assets/icons/sidebar_icon/project_blue_icon.png
  src/components/common/SideBar.tsx
Labels: HTML&CSS

#12 feature: add Carousel
  .eslintrc.json
  src/App.tsx
  src/assets/images/carousel/carousel1.png
  src/assets/images/carousel/carousel2.png
  src/components/home/HomeCarousel.tsx
  src/constants/home/carouselImg.ts
  src/pages/Home.tsx
Labels: Feature

#15 Feature/7 Commute 모달 기능/스타일 구현 완료
  src/assets/fonts/Font.css
  src/components/commute/CommuteButtonComponent.tsx
  src/components/commute/CommuteModal.tsx
  src/components/commute/StyleComponentCommute.tsx
Labels: Feature, HTML&CSS

#25 feat: 위키 및 갤러리 라우팅 설정
  src/App.tsx
  src/assets/icons/fontAwesome.txt
  src/components/SideBar/OfficeLife.tsx
  src/components/SideBar/Photos.tsx
  src/components/SideBar/SideBar.tsx
  src/components/common/Header.tsx
  src/components/gallery/Business.tsx
  src/components/gallery/JobPosting.tsx
  src/components/gallery/OfficePhoto.tsx
  src/components/wiki/office-life/CompanyRules.tsx
  src/components/wiki/office-life/OrganizationChart.tsx
  src/components/wiki/office-life/TeamIntroduction.tsx
  src/components/wiki/onboarding/ReadingList.tsx
  src/components/wiki/onboarding/Topics.tsx
  src/components/wiki/project/Completed.tsx
  src/components/wiki/project/InProject.tsx
  src/components/wiki/project/UpComing.tsx
  src/pages/Gallery.tsx
  src/pages/Wiki.tsx
  src/styles/SideBarStyle.tsx
Labels: Feature, HTML&CSS

#35 feature/#30 갤러리 페이지 라우팅, Wiki Editor Fix
  package-lock.json
  src/App.tsx
  src/components/SideBar/SideBar.tsx
  src/components/common/Header.tsx
  src/components/gallery/GallerySection.tsx
  src/components/wiki/MarkdownEditor.tsx
  src/components/wiki/WikiComponent.tsx
  src/pages/Gallery.tsx
Labels: API, Feature

#43 Feature/#41 이메일 로그인, 유저에게 권한 부여
  src/App.tsx
  src/assets/fonts/Font.css
  src/assets/icons/header_icon/header_commute_black_icon.png
  src/assets/icons/header_icon/header_dropdown_icon.png
  src/assets/icons/header_icon/header_login_icon.png
  src/assets/icons/header_icon/header_logout_icon.png
  src/assets/icons/header_icon/header_notice_icon.png
  src/components/common/Header.tsx
  src/components/commute/CommuteButtonComponent.tsx
  src/components/commute/CommuteModal.tsx
  src/components/commute/StyleComponentCommute.tsx
  src/components/gallery/GalleryDetailModal.tsx
  src/components/gallery/GallerySection.tsx
  src/components/wiki/WikiComponent.tsx
  src/context/AuthContext.tsx
  src/firebase.ts
  src/pages/Login.tsx
  src/pages/Signup.tsx
Labels: API, Feature, HTML&CSS

#44 feat: Home Gallery, Home Notice 기능 추가
  package-lock.json
  src/App.tsx
  src/assets/icons/footer_icon/footer_github_black_icon.png
  src/assets/icons/header_icon/header_notice_icon.png
  src/assets/icons/notice_icon/notice_write_icon.png
  src/components/common/Footer.tsx
  src/components/common/Header.tsx
  src/components/home/Calendar.tsx
  src/components/home/EventDetailModal.tsx
  src/components/home/HomeGallery.tsx
  src/components/home/HomeNotice.tsx
  src/components/notice/NoticeDetail.tsx
  src/components/wiki/MarkdownEditor.tsx
  src/components/wiki/MarkdownViewer.tsx
  src/components/wiki/WikiComponent.tsx
  src/pages/Gallery.tsx
  src/pages/Home.tsx
  src/pages/Notice.tsx
  src/pages/NoticeEditor.tsx
  src/pages/Wiki.tsx
  src/pages/index.ts
Labels: Setting, Feature, Refactor, HTML&CSS

#49 Feat:로그인 유효성검사
  src/pages/Login.tsx
  src/pages/Signup.tsx
Labels: Feature

#50 design: 공지사항 클릭 시 전환 css 추가
  src/pages/Notice.tsx
Labels: HTML&CSS

#58 Refactor: Home, Notice
  src/App.tsx
  src/components/common/Header.tsx
  src/components/commute/CommuteButtonComponent.tsx
  src/components/commute/CommuteModal.tsx
  src/components/home/AddEventModal.tsx
  src/components/home/Calendar.tsx
  src/components/home/EventDetailModal.tsx
  src/components/home/HomeGallery.tsx
  src/components/home/HomeNotice.tsx
  src/components/notice/NoticeDetail.tsx
  src/firebase.ts
  src/pages/Gallery.tsx
  src/pages/Home.tsx
  src/pages/NotFound.tsx
  src/pages/Notice.tsx
  src/pages/NoticeEditor.tsx
  src/pages/Wiki.tsx
  src/pages/index.ts
  src/types/home.ts
  src/types/notice.ts
Labels: Setting, API, Feature, Refactor, BugFix, HTML&CSS

#70 Feature/#68
  src/assets/icons/header_icon/hamburger_icon.png
  src/components/common/Header.tsx
  src/components/commute/CommuteButtonComponent.tsx
  src/components/commute/StyleComponentCommute.tsx
  src/components/home/Calendar.tsx
  src/components/home/EventDetailModal.tsx
  src/constants/dropDown.ts
  src/types/commute.ts
Labels: Feature, Refactor, HTML&CSS

#69 Feature/#64 로그인/회원가입, 출퇴근모달 css 수정
  src/components/commute/CommuteModal.tsx
  src/components/commute/StyleComponentCommute.tsx
  src/pages/Login.tsx
  src/pages/Signup.tsx
Labels: Refactor, HTML&CSS

#72 design: 전체적인 css 수정 및 반응형 구현
  src/components/common/Header.tsx
  src/components/common/Logo.tsx
  src/components/gallery/GalleryModal.tsx
  src/components/gallery/GallerySection.tsx
  src/components/home/Calendar.tsx
  src/components/home/HomeGallery.tsx
  src/components/home/HomeNotice.tsx
  src/components/sideBar/OfficeLife.tsx
  src/components/sideBar/Onboarding.tsx
  src/components/sideBar/Project.tsx
  src/components/sideBar/SideBar.tsx
  src/components/wiki/WikiComponent.tsx
  src/pages/Gallery.tsx
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/pages/Notice.tsx
  src/pages/NoticeEditor.tsx
  src/pages/Signup.tsx
  src/pages/Wiki.tsx
  src/styles/SideBarStyle.tsx
  src/types/userLog.ts
Labels: Feature, HTML&CSS
